version: '3.7'

networks:
  eventhub-network:
    external: true

services:
  postgresql:
    container_name: postgres
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    networks: 
      - eventhub-network